# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode10.1
before_install:
- gem install cocoapods xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild test -workspace SimpleAnimation.xcworkspace -scheme SimpleAnimation -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=12.1' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint --quick
- carthage build --no-skip-current
